---

- hosts: remote_web
  become: true
  become_user: root
  tasks:



  - name: copy Dockerfile into Remote machine

    copy:

      src: Dockerfile 

      dest: .
      
      chdir: /home/ec2-user

  - name: copy war file into Remote machine

    copy:

      src: /var/lib/jenkins/workspace/play1/webapp/target/webapp.war


      dest: .

  - name: Stop the running container

    command: docker stop mycontainer

    ignore_errors: True



  - name: remove the running container

    command: docker rm mycontainer

    ignore_errors: True



  - name: remove the running image

    command: docker rmi myimage

    ignore_errors: True



  - name: Create the image from Docker file

    command: docker build -t myimage .



  - name: Create and run container

    command: docker run -d -p 8080:8080 --name mycontainer myimage

