
---
- name: "Run Maven build on Jenkins CI server"
  hosts: localhost
  tasks:
  - name: Running mvn clean
    command: "mvn clean install"
    register: mvn_result

  - name: "mvn clean task output"
    debug:
      var: mvn_result
